...

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,11 +1,18 @@
 #!/bin/bash
 
+which sbt &> /dev/null
+
+if [[ "$?" != 0 ]]; then
+  echo "can't find sbt"
+  exit 1
+fi
+
 if [[ "$1" == "jar" ]]; then
 
   sbt assembly || exit 1
 
-  for f in $(ls -1 target | grep .jar | grep -v _executable.jar); do
-    tf=target/${f/.jar/}_executable.jar
+  for f in $(ls -1 target | grep .jar); do
+    tf=target/${f/.jar/}
     echo "#!/usr/bin/java -jar" > $tf
     cat target/$f >> $tf
     chmod +x $tf
